import json
import logging
import os
from datetime import datetime, timezone

from .provider import LLMProvider
from .providers.mock_provider import MockProvider
from .sanitizer import sanitize_case_for_llm
from .schemas import AIAnalysis
from .validator import validate_analysis

logger = logging.getLogger(__name__)


def _get_provider() -> LLMProvider:
    """Resolve the LLM provider from the environment.

    The OpenAI/Anthropic SDKs are imported lazily so the packaged demo build
    (USE_MOCK_AI=true) does not require or bundle them.
    """
    use_mock = os.environ.get("USE_MOCK_AI", "true").lower() in ("true", "1", "yes")
    if use_mock:
        logger.info("Using mock AI provider (USE_MOCK_AI=true)")
        return MockProvider()

    provider_name = os.environ.get("AI_PROVIDER", "openai").lower()
    if provider_name == "anthropic":
        logger.info("Using Anthropic AI provider")
        from .providers.anthropic_provider import AnthropicProvider

        return AnthropicProvider()
    logger.info("Using OpenAI AI provider")
    from .providers.openai_provider import OpenAIProvider

    return OpenAIProvider()


def _log_prompt(provider: LLMProvider, case: dict, sanitized: dict) -> None:
    logger.debug(
        "AI prompt — provider=%s case_id=%s",
        type(provider).__name__,
        case.get("case_id", "unknown"),
    )
    logger.debug("Sanitized case keys: %s", list(sanitized.keys()))


def _log_response(raw: str) -> None:
    truncated = raw[:500] + "..." if len(raw) > 500 else raw
    logger.debug("AI raw response (truncated): %s", truncated)


async def analyze_case(case: dict) -> AIAnalysis:
    provider = _get_provider()
    case_id = case.get("case_id", "unknown")

    sanitized = sanitize_case_for_llm(case)
    _log_prompt(provider, case, sanitized)

    raw_output = provider.analyze(sanitized)
    _log_response(raw_output)

    analysis, issues = validate_analysis(raw_output, case)
    if issues:
        logger.warning("Validation issues for case %s: %s", case_id, issues)

    if analysis is not None:
        logger.info("AI analysis validated successfully for case %s", case_id)
        return analysis

    logger.info("Retrying with stricter prompt for case %s", case_id)
    retry_case = dict(sanitized)
    retry_case["__instruction"] = (
        "IMPORTANT: Return ONLY valid JSON matching the AIAnalysis schema exactly. "
        "No markdown fences. No extra text. Every number in your response must come "
        "from the input data. Do not reference any CVE not present in the input."
    )
    raw_retry = provider.analyze(retry_case)
    _log_response(raw_retry)

    analysis, retry_issues = validate_analysis(raw_retry, case)
    if analysis is not None:
        logger.info("AI analysis validated on retry for case %s", case_id)
        return analysis

    logger.warning(
        "AI analysis failed validation for case %s (retry issues: %s), falling back to mock",
        case_id,
        retry_issues,
    )

    fallback_provider = MockProvider()
    raw_fallback = fallback_provider.analyze(case)
    analysis, fallback_issues = validate_analysis(raw_fallback, case)

    if analysis is None:
        logger.error("Even mock provider failed for case %s — returning minimal fallback", case_id)
        return AIAnalysis(
            summary=f"Mock analysis for case {case_id}",
            why_it_matters="Automated fallback — LLM analysis unavailable",
            evidence_summary="Evidence data present in case",
            priority_explanation="Priority determined by deterministic system",
            investigation_questions=["Review case details manually"],
            recommended_remediation=["Apply standard remediation procedures"],
            confidence_notes=["Fallback analysis — low confidence"],
            limitations=["Generated by mock fallback due to LLM failure"],
            model="mock-fallback",
            generated_at=datetime.now(timezone.utc).isoformat(),
            grounded_on=["case.case_id"],
        )

    return analysis
