"""Populates Kurukshetra_2.0_PPT_template.pptx with CyberYukti project data.
"""

import sys
import os
import pptx
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN, MSO_ANCHOR
from pptx.enum.shapes import MSO_SHAPE

SRC_FILE = r"d:\kuruk_hack\Kurukshetra_2.0_PPT_template.pptx"
OUT_FILE = r"d:\kuruk_hack\Kurukshetra_2.0_PPT_filled.pptx"

def set_text_safely(shape, text, font_size_pt=12, bold=False, color=None):
    if not shape.has_text_frame:
        return
    tf = shape.text_frame
    tf.word_wrap = True
    # Clear existing text
    p = tf.paragraphs[0]
    p.text = ""
    for extra in tf.paragraphs[1:]:
        extra.text = ""
    
    lines = text.strip().split("\n")
    for idx, line in enumerate(lines):
        if idx == 0:
            para = p
        else:
            para = tf.add_paragraph()
        para.text = line
        para.font.size = Pt(font_size_pt)
        para.font.bold = bold
        if color:
            para.font.color.rgb = color
        para.space_after = Pt(4)

def run():
    prs = pptx.Presentation(SRC_FILE)
    print(f"Loaded {SRC_FILE} with {len(prs.slides)} slides.")

    # Colors
    TEXT_MAIN = RGBColor(40, 44, 52)
    TEXT_MUTED = RGBColor(90, 95, 105)
    ACCENT_BLUE = RGBColor(14, 116, 144)

    # -------------------------------------------------------------------------
    # SLIDE 1: Cover
    # -------------------------------------------------------------------------
    s1 = prs.slides[0]
    for sh in s1.shapes:
        if sh.shape_id == 91:
            txt = (
                "•  Problem ID - PS16\n"
                "•  Problem Statement - Autonomous Vulnerability Triage & Evidence Engine\n"
                "•  Theme - Cyber & Blockchain\n"
                "•  Team ID - KH079\n"
                "•  Team name - Sudarshan_MITAOE"
            )
            set_text_safely(sh, txt, font_size_pt=18, bold=True)

    # -------------------------------------------------------------------------
    # SLIDE 2: Understanding the Problem
    # -------------------------------------------------------------------------
    s2 = prs.slides[1]
    for sh in s2.shapes:
        if sh.shape_id == 106:
            set_text_safely(sh, "Sudarshan_MITAOE", font_size_pt=12, bold=True)
        elif sh.shape_id == 110:
            txt = (
                "CyberYukti is an autonomous vulnerability triage and deterministic evidence validation engine "
                "that reduces alert noise generated by scanning tools into verified, prioritized, and analyst-ready security cases."
            )
            set_text_safely(sh, txt, font_size_pt=14, bold=True)
        elif sh.shape_id == 112:
            txt = (
                "• Alert Fatigue: 1 real flaw triggers 10+ alerts across Trivy, Semgrep, and Nuclei.\n"
                "• Stale & Ghost Findings: Up to 40% of scanner alerts flag libraries already patched in production or unexposed.\n"
                "• Naive AI Risks: Generic LLM wrappers hallucinate fake CVEs and are vulnerable to prompt-injection attacks in scanner outputs."
            )
            set_text_safely(sh, txt, font_size_pt=12)
        elif sh.shape_id == 114:
            txt = (
                "• Security Analysts (SOC, AppSec): Overwhelmed by alert volume and manual verification.\n"
                "• DevSecOps Engineers: Blocked by false-positive security tickets that stall CI/CD.\n"
                "• CISOs & Compliance Teams: Lack tamper-evident audit trails for SOC 2 / ISO 27001."
            )
            set_text_safely(sh, txt, font_size_pt=12)

    # -------------------------------------------------------------------------
    # SLIDE 3: Proposed Solution
    # -------------------------------------------------------------------------
    s3 = prs.slides[2]
    for sh in s3.shapes:
        if sh.shape_id == 106 or sh.name == "Google Shape;106;p3":
            set_text_safely(sh, "Sudarshan_MITAOE", font_size_pt=12, bold=True)
        elif sh.shape_id == 133:  # Solution Overview
            txt = (
                "• Idea / Solution: Dual-rail autonomous engine combining deterministic sandbox probes with bounded AI explanation.\n"
                "• Direct PS16 Alignment: Ingests multi-format scans, clusters duplicates (90.5% noise cut), safely probes sandbox targets, calculates math-based risk, and enforces human approval."
            )
            set_text_safely(sh, txt, font_size_pt=11.5)
        elif sh.shape_id == 135:  # Innovation & Uniqueness
            txt = (
                "• Dual-Rail Zero-Trust: LLM never decides security truth; mathematical code handles validation and scoring.\n"
                "• Dynamic Re-Prioritization: Live sandbox probes prove patched assets, auto-demoting priority (P2 → P3).\n"
                "• Poison-Proof AI: 24-field quarantine sanitizer prevents prompt-injection hijacking."
            )
            set_text_safely(sh, txt, font_size_pt=11.5)
        elif sh.shape_id == 137:  # Existing Solutions / Similar Work
            txt = (
                "• Conventional Tools (Jira, DefectDojo): Passive databases requiring manual verification.\n"
                "• Commercial ASPMs (Snyk, Wiz): Proprietary reachability with vendor lock-in.\n"
                "• CyberYukti Advantage: Cross-tool SAST × DAST × SCA reachability on open-source tools with SHA-256 hash chaining."
            )
            set_text_safely(sh, txt, font_size_pt=11.5)

    # -------------------------------------------------------------------------
    # SLIDE 4: Technical Approach
    # -------------------------------------------------------------------------
    s4 = prs.slides[3]
    for sh in s4.shapes:
        if sh.shape_id == 153:  # Team name
            set_text_safely(sh, "Sudarshan_MITAOE", font_size_pt=12, bold=True)
        elif sh.shape_id == 157:  # Technology Stack
            txt = (
                "• Languages & Frameworks: Python 3.12, FastAPI, Next.js 14, React 18, TypeScript, Tailwind CSS.\n"
                "• Validation Libraries: Pydantic v2, Python packaging.version, HTTPX, Docker SDK.\n"
                "• AI Engine: Dual-Rail Orchestrator (GPT-4o / Claude 3.5 / Local Mock) + Regex Sanitizer."
            )
            set_text_safely(sh, txt, font_size_pt=11)
        elif sh.shape_id == 159:  # Working / Implementation Approach
            txt = (
                "1. Ingestion: Parsers normalize Trivy, Semgrep, Nuclei, SARIF, and CSV into CanonicalFinding objects.\n"
                "2. Clustering: 3-tier dedup eliminates exact hash duplicates, generic CWEs, and correlates SAST routes with DAST endpoints.\n"
                "3. Sandbox Probes: Safe, read-only probes inspect target manifests, sockets, and endpoints.\n"
                "4. Deterministic Evaluation: Returns CONFIRMED, NOT_CONFIRMED, or INCONCLUSIVE.\n"
                "5. Dynamic Risk: Math formula computes P1–P4 score, AI explains, and analyst approves or overrides."
            )
            set_text_safely(sh, txt, font_size_pt=10.5)
        elif sh.shape_id == 163:  # Clear placeholder text in diagram box
            set_text_safely(sh, "")

    # Embed high-res architecture diagram image onto Slide 4
    arch_img_path = r"d:\kuruk_hack\cyberyukti_system_architecture.png"
    if os.path.exists(arch_img_path):
        # Center 16:9 image inside shape 162 bounding box
        pic_w = 5850000
        pic_h = int(pic_w * 9 / 16)
        pic_left = 5685435 + (5905101 - pic_w) // 2
        pic_top = 1881186 + (4202908 - pic_h) // 2
        s4.shapes.add_picture(arch_img_path, pic_left, pic_top, width=pic_w, height=pic_h)
        print("Embedded high-res system architecture diagram into Slide 4.")

    # -------------------------------------------------------------------------
    # SLIDE 5: Feasibility, Viability & Impact
    # -------------------------------------------------------------------------
    s5 = prs.slides[4]
    for sh in s5.shapes:
        if sh.shape_id == 176:
            set_text_safely(sh, "Sudarshan_MITAOE", font_size_pt=12, bold=True)
        elif sh.shape_id == 180:  # Feasibility & Viability
            txt = (
                "• Technical Feasibility: 100% operational; 93/93 automated tests pass across backend and frontend (80 pytest + 13 vitest).\n"
                "• Operational Viability: Runs containerized in Docker or lightweight CI/CD subprocess sandboxes.\n"
                "• Risk & Mitigation: Read-only probes with hard 5.0s timeouts and target allowlists eliminate target crash risk. Dual-rail prompt sanitization blocks prompt-injection hijacking."
            )
            set_text_safely(sh, txt, font_size_pt=11)
        elif sh.shape_id == 182:  # Impact & Benefits
            txt = (
                "• 90.5% Noise Cut: 42 raw scanner alerts collapse into 4 actionable incident clusters.\n"
                "• 31.5 Hours Saved: Saves ~25m per duplicate and ~45m per auto-probed patch ($3,150+ saved/cycle).\n"
                "• Instant MTTR: Triage turnaround drops from days to seconds.\n"
                "• Audit Ready: SHA-256 hash-chained ledger provides compliance non-repudiation."
            )
            set_text_safely(sh, txt, font_size_pt=11)
        elif sh.shape_id == 187:  # AI/ML Details
            txt = (
                "• Architecture: Dual-Rail Guarded Pipeline (GPT-4o / Claude 3.5 / Local Mock Provider).\n"
                "• Prompt Defense: 24-field sanitizer quarantines untrusted text in <UNTRUSTED> delimiters.\n"
                "• Grounding Validator: Enforces strict JSON schema and verifies that all CVEs and CVSS numbers in the output exist in the input (16/16 adversarial injection tests passed)."
            )
            set_text_safely(sh, txt, font_size_pt=11)

    # -------------------------------------------------------------------------
    # SLIDE 6: Research & References
    # -------------------------------------------------------------------------
    s6 = prs.slides[5]
    for sh in s6.shapes:
        if sh.shape_id == 200:
            set_text_safely(sh, "Sudarshan_MITAOE", font_size_pt=12, bold=True)
        elif sh.shape_id == 204:  # Research Conducted
            txt = (
                "• Standards: NIST SP 800-115 (Information Security Testing), OWASP Top 10 for LLMs (2025), FIRST EPSS v3, CISA KEV.\n"
                "• Academic Papers & Frameworks: First.org EPSS probability modeling, GitLab multi-scanner deduplication heuristics."
            )
            set_text_safely(sh, txt, font_size_pt=11.5)
        elif sh.shape_id == 206:  # References / Sources
            txt = (
                "• FIRST EPSS Framework: https://www.first.org/epss/\n"
                "• CISA KEV Catalog: https://www.cisa.gov/known-exploited-vulnerabilities-catalog\n"
                "• National Vulnerability Database (NVD): https://nvd.nist.gov/\n"
                "• OWASP LLM Top 10: https://owasp.org/www-project-top-10-for-large-language-model-applications/"
            )
            set_text_safely(sh, txt, font_size_pt=11)
        elif sh.shape_id == 210:  # GitHub Repository
            txt = (
                "Team's public GitHub repository URL:\n"
                "https://github.com/Sahas2711/CyberYukti\n"
                "(Active Implementation Branch: person-2-evidence-engine)"
            )
            set_text_safely(sh, txt, font_size_pt=13, bold=True)

    # -------------------------------------------------------------------------
    # SLIDE 7: Build With
    # -------------------------------------------------------------------------
    s7 = prs.slides[6]
    for sh in s7.shapes:
        if sh.shape_id == 224:
            set_text_safely(sh, "Sudarshan_MITAOE", font_size_pt=12, bold=True)
    
    # Add structured cards onto Slide 7
    # 2 columns x 3 rows
    cards = [
        ("Frontend", "• Next.js 14 (React 18 App Router)\n• TypeScript 5.6 & Tailwind CSS 3.4\n• Lucide Icons & Responsive Panels\n• Live interactive probe execution", Inches(0.8), Inches(1.8)),
        ("Backend", "• FastAPI 0.115 & Python 3.12\n• Pydantic v2 Strict Data Contracts\n• Uvicorn ASGI with Lifespan state\n• HTTPX Async HTTP Probe Client", Inches(4.7), Inches(1.8)),
        ("Database & Ledger", "• Thread-Safe In-Memory Case Store\n• Synchronized Ingestion Cluster Index\n• Cryptographic SHA-256 Hash Chain\n• prev_hash Non-Repudiation", Inches(8.6), Inches(1.8)),
        ("AI / ML Guardrails", "• Dual-Rail Orchestrator (GPT-4o/Claude)\n• 24-Field Prompt Quarantine Sanitizer\n• Schema Output Grounding Validator\n• 16/16 Adversarial Tests Passed", Inches(0.8), Inches(4.2)),
        ("Tools & Validation", "• Docker & Docker Compose Isolation\n• Pytest (77 Python backend tests)\n• Vitest (13 TypeScript tests)\n• Trivy, Semgrep, Nuclei Parsers", Inches(4.7), Inches(4.2)),
        ("Architecture Principles", "• Dual-Rail Zero-Trust (Code proves, AI explains)\n• Fail-Safe Bounded Probes (Timeouts = Inconclusive)\n• Zero Autonomous Exploitation (No weaponization)\n• 90.5% Alert Noise Elimination", Inches(8.6), Inches(4.2)),
    ]

    for title, body, left, top in cards:
        card = s7.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE, left, top, Inches(3.6), Inches(2.2))
        card.fill.solid()
        card.fill.fore_color.rgb = RGBColor(248, 250, 252)
        card.line.color.rgb = RGBColor(203, 213, 225)
        card.line.width = Pt(1)
        
        tf = card.text_frame
        tf.word_wrap = True
        tf.vertical_anchor = MSO_ANCHOR.TOP
        tf.margin_left = Inches(0.18)
        tf.margin_right = Inches(0.18)
        tf.margin_top = Inches(0.18)
        tf.margin_bottom = Inches(0.15)
        
        p0 = tf.paragraphs[0]
        p0.text = title
        p0.font.size = Pt(14)
        p0.font.bold = True
        p0.font.color.rgb = RGBColor(14, 116, 144)
        p0.space_after = Pt(6)

        for line in body.split("\n"):
            p = tf.add_paragraph()
            p.text = line
            p.font.size = Pt(10.5)
            p.font.color.rgb = RGBColor(51, 65, 85)
            p.space_after = Pt(2)

    # -------------------------------------------------------------------------
    # SLIDE 8: Thank You
    # -------------------------------------------------------------------------
    s8 = prs.slides[7]
    for sh in s8.shapes:
        if sh.shape_id == 263:
            set_text_safely(sh, "Sudarshan_MITAOE", font_size_pt=12, bold=True)
    
    # Add subtitle under THANK YOU
    thanks_box = s8.shapes.add_textbox(Inches(2.5), Inches(4.2), Inches(8.333), Inches(1.5))
    tf_th = thanks_box.text_frame
    tf_th.word_wrap = True
    p_th1 = tf_th.paragraphs[0]
    p_th1.text = "CyberYukti — Autonomous Vulnerability Triage & Evidence Engine"
    p_th1.alignment = PP_ALIGN.CENTER
    p_th1.font.size = Pt(18)
    p_th1.font.bold = True
    p_th1.font.color.rgb = RGBColor(14, 116, 144)

    p_th2 = tf_th.add_paragraph()
    p_th2.text = "Questions & Answers  •  GitHub: https://github.com/Sahas2711/CyberYukti"
    p_th2.alignment = PP_ALIGN.CENTER
    p_th2.font.size = Pt(14)
    p_th2.font.color.rgb = RGBColor(100, 116, 139)

    prs.save(OUT_FILE)
    print(f"[SUCCESS] Saved filled presentation to: {OUT_FILE}")

if __name__ == "__main__":
    run()
